import QueryProvider from "@/context/query";
import "./globals.css";
import { Inter } from "next/font/google";
import SearchButton from "@/components/search-button";
import { Button } from "@/components/ui/button";
import { Shapes } from "lucide-react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <header className="relative border-border border mb-2 shadow-sm">
            <nav className="container flex justify-between h-12 items-center">
              <Button variant="link" asChild>
                <Link href="/">
                  <Shapes />
                </Link>
              </Button>
              <SearchButton></SearchButton>
            </nav>
          </header>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
